DROP TABLE IF EXISTS artist;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS tracks;


CREATE TABLE artist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  artist_name TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);


CREATE TABLE genres (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT,
  title VARCHAR NOT NULL
);

CREATE TABLE tracks (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT,
  title VARCHAR NOT NULL,
  artist VARCHAR NOT NULL,
  length DECIMAL NOT NULL,
  genre_id INTEGER NOT NULL,
  FOREIGN KEY (genre_id) REFERENCES genres(id),
  FOREIGN KEY (artist) REFERENCES artist(artist_name)
);